Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.network "private_network", ip: "192.168.56.11"
  config.vm.define "minion"
  config.vm.hostname = "minion"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end
  config.vm.provision :salt do |salt|
    salt.minion_config = "salt/config"
    salt.minion_key = "../ssh-keys/minion.pem"
    salt.minion_pub = "../ssh-keys/minion.pub"
    salt.install_type = "stable"
    salt.verbose = true
    salt.colorize = true
  end
end
